name: Release

on:
  push:
    tags:
      - '*.*.*'

env:
  POETRY_VERSION: 1.5.1

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
        # IMPORTANT: this permission is mandatory for trusted publishing
        id-token: write
        contents: read # See https://github.com/actions/checkout/issues/254#issuecomment-981945812
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Bootstrap poetry
        run: |
          curl -sSL https://install.python-poetry.org | python - -y

      - name: Update PATH
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Build project for distribution
        run: poetry build

      - name: Build new documentation
        run: mkdocs gh-deploy

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
